# Generated by Django 4.2.4 on 2024-01-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Predict', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_image_path', models.CharField(max_length=100, null=True)),
                ('project_alt', models.CharField(max_length=100, null=True)),
                ('project_title', models.CharField(max_length=100, null=True)),
                ('project_description', models.TextField()),
                ('project_link', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CarBrand',
        ),
    ]
