# Generated by Django 4.2.4 on 2024-01-08 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_image_path', models.CharField(blank=True, max_length=100, null=True)),
                ('project_alt', models.CharField(blank=True, max_length=100, null=True)),
                ('project_title', models.CharField(blank=True, max_length=100, null=True)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('project_link', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
