# Generated by Django 4.2.4 on 2024-01-09 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='project_link',
        ),
    ]
